/** @type {import('next').NextConfig} */
const nextConfig = {
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    unoptimized: true,
  },
  serverExternalPackages: [
    "jsonresume-theme-elegant",
    "jsonresume-theme-flat",
    "jsonresume-theme-even",
    "jsonresume-theme-kendall",
    "jsonresume-theme-macchiato",
    "jsonresume-theme-pumpkin",
    "jsonresume-theme-modern",
    "jsonresume-theme-short",
    "jsonresume-theme-paper",
    "jsonresume-theme-tan-responsive",
    "jsonresume-theme-rickosborne",
    "jsonresume-theme-eloquent",
    "jsonresume-theme-onepage-plus",
    "jsonresume-theme-autumn",
    "jsonresume-theme-spartan",
    "jsonresume-theme-minimal",
    "jsonresume-theme-crisp",
    "jsonresume-theme-stackoverflow",
    "jsonresume-theme-straightforward",
    "jsonresume-theme-modern-extended",
    "jsonresume-theme-rnord",
    "jsonresume-theme-light-classy-responsive",
    "jsonresume-theme-simplyelegant",
    "jsonresume-theme-projects",
    "jsonresume-theme-msresume",
    "jsonresume-theme-dark-classy-responsive",
    "jsonresume-theme-onepage",
    "jsonresume-theme-slick",
    "jsonresume-theme-rocketspacer",
    "jsonresume-theme-direct",
    "jsonresume-theme-compact",
    "jsonresume-theme-clean",
    "jsonresume-theme-actual",
  ],
  output: "standalone",
};

export default nextConfig;
